### ISSUE TITLE
Hodnocení od Matěje

### ISSUE THREAD

**Issue by Amatthe** [LucieMusilova/Ukol_1_zivotopis#1]
Ahoj,
za mě to vypadá dobře. Vidím ještě trochu prostoru ke zlepšení v pozicování prvků na stránce, třeba u těch znalostí vidím takové okno mezi obsahem a obrázkem. Ale to všechno se ještě naučíš a mnohem víc :)

**Comment by LucieMusilova** [comment]
Ahoj Matěji, děkuju. :) Jo, já to i původně chtěla dělat trochu jinak, ale zjistila jsem, že jsou na to potřeba ty sloupce. Tak se těším, jak se všechno naučím.:)
